platform:ios,'7.1'
target 'PROJECT' do
pod 'AFNetworking', '~> 3.1.0'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'SDWebImage', '~> 4.0.0-beta2'
pod 'Reachability', '~> 3.2'
pod 'JazzHands', '~> 2.0.8'
pod 'SDCAlertView'
pod 'MJExtension', '~> 3.0.13'
pod 'MJRefresh', '~> 3.1.12'
pod 'WebViewJavascriptBridge', '~> 5.0.7'
pod 'iOS-Categories', '~> 1.0.2'
pod 'YTKNetwork', '~> 2.0.3'
end
